accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("register", views.registerView, name="register"),
    path("login", views.loginView, name="login"),
    path("staff_dashboard", views.staff_dashboard, name="staff_dashboard"),
    path("approve/<int:id>", views.approve, name="approve"),
    path("applicant_dashboard", views.applicant_dashboard, name="applicant_dashboard"),
    path("applicant_profile/<int:id>", views.applicant_profile, name="applicant_profile"),
    path("update_profile", views.update_profile, name='update_profile'),
]

bursaryapp/urls.py
from django.urls import path
from . import views

app_name = 'bursaryapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path("Addbursary/", views.Addbursary, name="Addbursary"),
    path("Addparameters/<int:id>'", views.Addparameters, name="Addparameters"),
    path("Editbursary/<int:id>'", views.Editbursary, name="Editbursary"),
    path("Generateapplicants/<int:id>'", views.Generateapplicants, name="Generateapplicants"),
    
    path("bursary/<int:id>'", views.bursary_details, name="bursary_details"),
    path("Applicants/'", views.Applicants, name="Applicants"),
    path("applyBursary/<int:id>'", views.applyBursary, name="applyBursary"),
    # path('bursary/<int:pk>', views.BursaryDetailView.as_view(), name='bursary_details'),
]

pbursary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bursaryapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bursaryapp/models.py
from xml.parsers.expat import model
from django.db import models
from django.urls import reverse
# from pbursary.util import unique_slug_generator
from django.db.models.signals import pre_save

from accounts.models import Applicant
# from django.dispatch import receiver

# Create your models here.
class Bursary(models.Model):
    name_of_bursary = models.CharField(max_length=300)
    start_date = models.DateField(auto_now_add = False, auto_now = False)
    end_date = models.DateField(auto_now_add = False, auto_now = False)
    description = models.TextField()
    # slug = models.SlugField(null=False, unique=True, blank=True)

    def __str__(self):
        return self.name_of_bursary
    
# @receiver(pre_save, sender= Bursary)
# def pre_save_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = unique_slug_generator(instance)


    def get_absolute_url(self):
        return reverse("bursaryapp:Addbursary", kwargs={"id": self.id})

    def get_update_url(self):
        return reverse("bursaryapp:Addparameters", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("bursaryapp:Editbursary", kwargs={"id": self.id})

    def get_parameters_children(self):
        return self.bursaryparameter_set.all()

class BursaryParameter(models.Model):
    bursary = models.ForeignKey(Bursary,on_delete=models.CASCADE, null=True)
    parameter = models.CharField(max_length=300, null=True)
    parameter_value = models.IntegerField(null=True)

    def __str__(self):
        if self.parameter:
            return self.parameter + ' - '+ str(self.bursary)
        else:
            return 'empty parameter'

    def get_absolute_url(self):
        return self.bursary.get_absolute_url()
        
class Application(models.Model):
    bursary_application = models.ForeignKey(Bursary,on_delete=models.CASCADE, null=True)
    applicant = models.ForeignKey(Applicant,on_delete=models.CASCADE, null=True)
    date_of_application = models.DateTimeField(auto_now_add=True, auto_now=False)
    score = models.IntegerField(default=0)
    status = models.BooleanField(null=True)

    def __str__(self):
            return str(self.applicant) +' application for '+  str(self.bursary_application)

            

bursaryapp/forms.py
from django import forms
from urllib import request

from accounts.models import Applicant
from . models import Application, Bursary, BursaryParameter
from  django.utils.translation import gettext_lazy as _
from multiselectfield import MultiSelectField

# CHOICES = BursaryParameter.objects.all().values_list('parameter','parameter').distinct()
querry = BursaryParameter.objects.all().values_list('parameter','parameter_value').distinct()

tups = []


for item in querry:
    tups.append(item)

parameters_dict = dict(tups)

# print(parameters_dict)

# choice_list = []

# for item in querry:
#     print(item[0])
#     if item[0] not in choice_list:
#         choice_list.append(item)


class AddBursaryForm(forms.ModelForm):
    class Meta:
        model = Bursary
        fields = '__all__'
        exclude = ['slug']

        widgets = {
            'name_of_bursary' : forms.TextInput(attrs={'class': 'form-control',}),
            'start_date' : forms.DateInput(attrs={'class': 'form-control'}),
            'end_date' : forms.DateInput(attrs={'class': 'form-control'}),
            'description' : forms.Textarea(attrs={'class': 'form-control'}),
        }

    # labels = {
    #     'name' : _('Hostel Name'),
    #     'rent' : _('Price per room in Ksh'),
    #     'dist' : _('Approximate distance from school'),           
    # }

class AddParameterForm(forms.Form):
    parameter = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), queryset=BursaryParameter.objects.all(), required=False)
    

class AddParametersForm(forms.ModelForm):
    class Meta:
        model = BursaryParameter
        fields = ['parameter','parameter_value']

class BursaryParametersForm(forms.ModelForm):

    # field_name = forms.ModelMultipleChoiceField(queryset=ModelClassName.objects.all(),
    #                                        to_field_name='model_class_field_name', 
    #                widget=forms.CheckboxSelectMultiple())

    # choices = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
    #                   choices=choice_list)

    class Meta:
        model = BursaryParameter
        fields = ['parameter','parameter_value']
        #exclude = ['bursary']

class ApplicationForm(forms.ModelForm):
    
    class Meta:
        model = Application
        fields = ['bursary_application','applicant','score']

        widgets = {
            'bursary_application' : forms.TextInput(attrs={'class': 'form-control',}),
            'applicant' : forms.DateInput(attrs={'class': 'form-control',}),
            'score' : forms.TextInput(attrs={'class': 'form-control',}),
        }

bursaryapp/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView
from django.contrib import messages
from django.forms.models import modelformset_factory
from django.contrib.auth.decorators import login_required
from accounts.decorators import unapproved_users
from .models import Application, Bursary, BursaryParameter
from .forms import AddBursaryForm, AddParametersForm, ApplicationForm, BursaryParametersForm
from accounts.models import Applicant
import json


# User = get_user_model()

# Create your views here.
class HomeView(ListView):
    model = Bursary
    template_name = 'home.html'

def bursary_details(request, id=None):
    obj = get_object_or_404(Bursary, id=id)
    queryset = BursaryParameter.objects.exclude(parameter__isnull=True).exclude(parameter__exact='').filter(bursary=obj)
    #SELECT * FROM BursaryParameter WHERE parameter IS NOT NULL AND parameter != ""

    context = {
        "bursary" : obj,
        "parameter" : queryset,
    }
    return render(request, 'bursary_details.html', context)

def Addbursary(request):
    bursary_form = AddBursaryForm(request.POST or None)
    context = {
        "bursary_form" : bursary_form
    }
    if bursary_form.is_valid():
        obj = bursary_form.save(commit=False)
        obj.save()
        return redirect(obj.get_update_url())
        # return redirect('bursaryapp:Editbursary')
    return render(request, 'Addbursary.html', context)

def Addparameters(request, id=None):
    obj = get_object_or_404(Bursary, id=id)
    bursary_form = AddBursaryForm(request.POST or None, instance=obj)
    parameters_form = AddParametersForm(request.POST or None)
    
    querry = BursaryParameter.objects.all().values_list('parameter','parameter_value').distinct()
    tups = []
    for item in querry:
        tups.append(item)
    parameters_dict = dict(tups)    
    print(tups)

    if bursary_form.is_valid and parameters_form.is_valid():
        parent = bursary_form.save(commit=False)
        parent.save()

        param_list = request.POST.getlist('parameter')
        print(param_list)
        val_list = request.POST.getlist('parameter_value')
        

        param_val_list = []

        for item in val_list:
            if item != '':
                param_val_list.append(item)
        
        print(param_val_list)        

        L3 = []
        for x in range(len(param_list)):
            L3.append((param_list[x], param_val_list[x]))

        print(L3)

        param_dict = dict(L3)
        print(param_dict)

        for param in param_dict:
            obj = BursaryParameter()
            obj.parameter = param
            obj.parameter_value = param_dict[param]
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print(obj.parameter)
            print(obj.parameter_value)
            if obj.bursary is None:
                obj.bursary = parent
            print(obj)
            obj.save()
            print("Added New Parameters")
        return redirect('accounts:staff_dashboard') 
    context = {
        "bursary" : obj,
        "bursary_form":bursary_form,
        "parameters_form":parameters_form,
        "parameters_dict" : parameters_dict,    
    }
    return render(request, 'Addparameters.html', context)


def Editbursary(request, id=None):
    obj = get_object_or_404(Bursary, id=id)
    bursary_form = AddBursaryForm(request.POST or None, instance=obj)
    ParametersFormset = modelformset_factory(BursaryParameter, form=BursaryParametersForm, extra=0)
    qs = obj.bursaryparameter_set.all()
    formset = ParametersFormset(request.POST or None, queryset=qs)
    context = {
        "bursary_form":bursary_form,
        "formset":formset,
        "object": obj,
    }
    if all([bursary_form.is_valid(), formset.is_valid()]):
        parent = bursary_form.save(commit=False)
        parent.save()
        for form in formset:
            child = form.save(commit=False)

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print(child.parameter)
            print(child.parameter_value)
            if child.parameter == None or child.parameter_value == None:
                print("ignore this empty")
            else:
                if child.bursary is None:
                    print("Added New Parameters")
                    child.bursary = parent
                print(child)
                child.save()
        context['message'] = 'Data saved.'
        return redirect('/')
    return render(request, 'Editbursary.html', context)


@login_required(login_url='accounts:login')
@unapproved_users
def applyBursary(request, id=None):
    parent = get_object_or_404(Bursary, id=id,)
    applicant_profile = Applicant.objects.get(user=request.user)
    initial = {'bursary_application': parent, 'applicant':applicant_profile, 'score':'0'}
    applicant_form = ApplicationForm(request.POST or None, initial= initial)
    qs = parent.bursaryparameter_set.all()
    querry = BursaryParameter.objects.filter(bursary_id = parent).values_list('parameter','parameter_value').distinct()

    tups = []


    for item in querry:
        tups.append(item)

    parameters_dict = dict(tups)
    
    context = {
        "bursary" : parent,
        "applicant_form" : applicant_form,
        "applicant_profile":applicant_profile,
        "parameters_dict":json.dumps(parameters_dict),
    }
    if applicant_form.is_valid():
        instance = applicant_form.save(commit=False)
        if Application.objects.filter(bursary_application=instance.bursary_application, applicant=instance.applicant).exists():
            url = request.META.get('HTTP_REFERER', '/')
            resp_body = '<script>alert("You have already applied for this bursary");\
             window.location="%s"</script>' % url
            # messages.info(request, "You have already applied for this bursary")
            print("You have already applied for this bursary")
            return HttpResponse(resp_body)
        else:
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print(instance.bursary_application)
            print(instance.applicant)
            print(instance.score)
            print(instance,'Succesful.')
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            instance.save()
            context['message'] = 'Application Succesful.'
            return redirect('/')
    return render(request, 'applyBursary.html', context)

def Generateapplicants(request, id=None ):
    obj = get_object_or_404(Bursary, id=id)
    # applicant = Applicant.objects.get(user=request.user)
    applications = Application.objects.filter(bursary_application = obj).order_by('-score')
    context = {
        "bursary":obj,
        "applications":applications,
        # "applicant":applicant,
    }
    return render(request, 'Generateapplicants.html', context)

def Applicants(request):
    applicants = Applicant.objects.all().order_by('user')
    context = {
        "applicants":applicants,
    }
    return render(request, 'Applicants.html', context)

bursaryapp/templates/Addbursary.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="d-flex justify-content-center">
    
    <form  method="post">
        <h1>Add New Bursary</h1>
        {% csrf_token %}
        {{ bursary_form|crispy }}
        <br>
        <div class="d-flex justify-content-center button-div">
            <button class="btn custom-btn" type="submit">Save</button>
        </div>

        <!-- <button type="submit">Save</button> -->
    </form>

</div>

{% endblock %}

bursaryapp/templates/Addparameters.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex justify-content-center">


<div class="d-flex justify-content-center">

<form method="POST" enctype="multipart/form-data">
    <h1>Add parameters for bursary</h1>
    {% csrf_token %}

    {{ bursary_form}}
    
    
    {% if parameters_form %}

        {% for key, value in parameters_dict.items %}
        
        <input type="checkbox" id="{{key}}" value="{{key}}" name="parameter">
        <label for="{{key}}"> {{ key }} </label><br />
        <label for="parameter_value"> parameter_value </label>
        <input type="text" id="parameter_value" value="{{value}}" name="parameter_value">
        <br />

        {% endfor %}

    {% endif %}
    <br />

    <div class="d-flex justify-content-center button-div">
        <button class="btn custom-btn" type="submit">Submit</button>
    </div>

</form>

<!-- {% if parameters_form %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        Parameters
         <br/>
         {% for key, value in parameters_form.parameter.field.choices %}
         <p>{{key}} : {{value}}</p>
             <input type="checkbox" id="{{value}}" value="{{key}}" name="parameter">
                 <label for="{{value}}">
                     {{ value }}
                 </label>
                 <br />
         {% endfor %} 

         <input type="submit" value="Save">
      </div>
</form>
{% endif %} -->

</div>
</div>
{% endblock %}

bursaryapp/templates/Applicants.html
{% extends 'base.html'%}

{% block header %}
        <div class="row d-flex flex-row">
            
            <div class="col-4 col-lg-6">
                <div class="d-flex form-inputs">
                    <input class="form-control" type="text" placeholder="Search">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            <div class="col-8 col-lg-6">

                <div class="navbar">
                    <a class="active" href="{% url 'bursaryapp:home' %}">&nbsp&nbsp&nbsp&nbspHome <i class="fa fa-home fa-fw"></i> </a>
                    {% if user.is_authenticated %}
                    {% if user.is_staff %}
                    <a href="{% url 'bursaryapp:Applicants' %}"> Applicants </i></a>
                    <a href="{% url 'bursaryapp:Addbursary' %}"> Add Bursary </i></a>
                    {% else %}
                    <a href="{% url 'accounts:applicant_dashboard' %}"> My profile <i class="fa fa-fw fa-user"></i></a>
                    {% endif %}
                    <a href="{% url 'logout' %}"> Logout <i class="fa fa-power-off"></i> &nbsp&nbsp&nbsp&nbsp</a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}"> Login <i class="fa fa-sign-in"></i> &nbsp&nbsp&nbsp&nbsp</a>
                    {% endif %} 
                </div>
            </div>    
        </div>
        {% endblock %}

{% block content%}

<div class="body-container pt-lg-4">
    <div class="container-lg">
        <div class="d-flex justify-content-center"><h2>Applicants</h2></div>
    

    {% for applicant in applicants %}

        <div class="row mb-5 applicant-row shadow-sm">
            <div class="col d-flex justify-content-center"><h5><a href="#">{{ applicant }} </a></h5></div>
        
            <div class="col d-flex justify-content-center align-items-center">
                {% if applicant.approved == False %}
                    <a class="btn btn-danger approve-badge" href="{% url 'accounts:approve' applicant.pk %}" role="button">approve</a>
                    <!-- <button type="button" class="btn btn-danger approve-badge">Approve</button> -->
                    <!-- <a href="#" class="approve-badge">Not Approved </a> -->
                {% else %}
                    <a class="approved-badge">Approved </a>
                {% endif %}
            </div>
            
            <div class="col d-flex justify-content-center align-items-center">
                <a href="{% url 'accounts:applicant_profile' applicant.pk %}" class="badg-blue">View account </a>
            </div>
        </div>

    {% endfor %}
</div>
</div>

{% endblock %}

bursaryapp/templates/Editbursary.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
<h1>Edit Bursary form</h1>

<form  method="post">
    {% csrf_token %}
    {{ bursary_form.as_p }}
    {% if formset %}
    <h3>Bursary Parameters</h3>
    {{ formset.management_form}}
    <div id="parameter-form-list">
        {% for form in formset %}
            <div class="parameter-form">
                {{ form|crispy }}
            </div>
        {% endfor %}
    </div>
    <div id="empty-form" class="hidden">{{ formset.empty_form.as_p }}</div>
    <button id="add-more" type="button">Add New Parameter</button>


    {% endif %}

    <button type="submit">Save changes</button>
</form>
</div>

<script>
    
    const addMoreBtn = document.getElementById("add-more")
    const totalNewForms = document.getElementById("id_form-TOTAL_FORMS")
    

    addMoreBtn.addEventListener("click", add_new_form)
    function add_new_form(event) {
        if (event) {
            event.preventDefault()
        }
        const currentParameterForms = document.getElementsByClassName("parameter-form")
        const currentFormCount = currentParameterForms.length + 1

        const formCopyTarget = document.getElementById("parameter-form-list")
        const copyEmptyFormEl = document.getElementById("empty-form").cloneNode(true)
        copyEmptyFormEl.setAttribute("class", "parameter-form")
        copyEmptyFormEl.setAttribute("id", `form-${currentFormCount}`)
        const regex = new RegExp('__prefix__', 'g')
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
        totalNewForms.setAttribute('value', currentFormCount + 1)


        //now add new empty form element to our html form
        formCopyTarget.append(copyEmptyFormEl)
    }
</script>

{% endblock %}

bursaryapp/templates/Generateapplicants.html
{% extends 'base.html'%}

{% block content%}
<br />
<br />
<div class="container">
    <div class="row">
        <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">{{ bursary.name_of_bursary }}</h5>
                <small class="text-muted d-flex justify-content-center">00 days : 00 hours : 00 mins</small>
            </div>
        </div>
    </div>

    <div class="mt-3">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Sr No.</th>
                    <th scope="col">Applicant</th>
                    <th scope="col">Score points</th>
                </tr>
            </thead>
            {% for application in applications%}
            <tr>
                <!-- {{application.applicant.user.first_name }} ------ {{application.bursary_application}} <br> -->
                <td> {{ forloop.counter }} </td>
                <td> {{ application.applicant.user.first_name }}  {{application.applicant.user.last_name }}  </td>
                <td> {{ application.score }} </td>
            </tr>
            {% endfor %}
        </table>
    </div>
        
        
        
    

</div>


{% endblock %}

bursaryapp/templates/bursary_details.html
{% extends 'base.html'%}

{% block content %}

<br />
<br />

<div class="container-lg">
    <div class="row">
        <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-center">{{ bursary.name_of_bursary }}</h5>
                <small class="text-muted d-flex justify-content-center">00 days : 00 hours : 00 mins</small>
            </div>
        </div>
    </div>
    <br>
    
    {% if user.is_staff %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ bursary.name_of_bursary }}</h5>
                <p class="card-text">View and edit bursary details.</p>
                <div class="d-flex justify-content-end button-div">
                    <a class="btn custom-btn btn-lg" href="{% url 'bursaryapp:Editbursary' bursary.pk %}" role="button">Edit</a>
                </div>
              </div>
            </div>
          </div>
        <!-- <div class="col-sm-6">
            <div class="card mb-3" style="max-width: 540px;"> 
                <div class="row no-gutters">
                  <div class="col-md-4">
                    
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{ bursary.name_of_bursary }}</h5>
                      <p class="card-text">View and edit bursary details.</p>
                      <div class="d-flex justify-content-end button-div">
                        <a class="btn custom-btn btn-lg" href="{% url 'bursaryapp:Editbursary' bursary.pk %}" role="button">Edit</a>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
        </div> -->
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">View Applications</h5>
              <p class="card-text">View all applicants and generate list of those qualified.</p>
              <div class="d-flex justify-content-end button-div">
                <a class="btn custom-btn btn-lg" href="{% url 'bursaryapp:Generateapplicants' bursary.pk %}" role="button">View</a>        
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

    <div>
        <div><h4>Description</h4></div>
        <div style="width:100%; overflow-wrap: break-word;">{{ bursary.description }}</div>
        <br>
        <div> Application Starts on : {{ bursary.start_date }} <br> </div>
        <div> Application Closes on : {{ bursary.end_date }} <br> </div>

        

        {% if user.is_staff %}

        <div class="mt-3"> Bursary Owner : Brian Ambeyi <br> </div>
        <div class="mt-3"> Bursary Parameters With Points <br> </div>

        <div class="row d-flex justify-content-start">
            <div class="col-md-6 pr-0">
                <div class="raw">
                    <table>
                        <thead>
                        <tr>
                            <th colspan="2">Parameter</th>
                            <th>parameter_value</th>
                          </tr>
                        </thead> 
                    <tbody>
                    {% for p in parameter %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ p.parameter}} </td>
                        <td> {{ p.parameter_value }} </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                    </div> 
             </div>
        </div>

        <!-- Birthday:<input type="date" name="bday">  Simple date input html 5 --> 
        
        <br>
        <!-- <div class="d-flex justify-content-end button-div">
            <a class="btn custom-btn btn-lg" href="{% url 'bursaryapp:Editbursary' bursary.pk %}" role="button">Edit</a>
        </div>
        <br> -->
        {% else %}
        <div class="d-flex justify-content-end button-div">
            <a class="btn custom-btn enlarge-btn btn-lg" href="{% url 'bursaryapp:applyBursary' bursary.pk %}" role="button">Apply</a>
        </div>
        {% endif %}
    </div>
</div>



{% endblock%}