accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("register", views.registerView, name="register"),
    path("login", views.loginView, name="login"),
    path("staff_dashboard", views.staff_dashboard, name="staff_dashboard"),
    path("approve/<int:id>", views.approve, name="approve"),
    path("applicant_dashboard", views.applicant_dashboard, name="applicant_dashboard"),
    path("applicant_profile/<int:id>", views.applicant_profile, name="applicant_profile"),
    path("update_profile", views.update_profile, name='update_profile'),
]

bursaryapp/urls.py
from django.urls import path
from . import views

app_name = 'bursaryapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path("Addbursary/", views.Addbursary, name="Addbursary"),
    path("Addparameters/<int:id>'", views.Addparameters, name="Addparameters"),
    path("Editbursary/<int:id>'", views.Editbursary, name="Editbursary"),
    path("Generateapplicants/<int:id>'", views.Generateapplicants, name="Generateapplicants"),
    
    path("bursary/<int:id>'", views.bursary_details, name="bursary_details"),
    path("Applicants/'", views.Applicants, name="Applicants"),
    path("applyBursary/<int:id>'", views.applyBursary, name="applyBursary"),
    # path('bursary/<int:pk>', views.BursaryDetailView.as_view(), name='bursary_details'),
]

pbursary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bursaryapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load django_htmx %}


{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>#</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.css' %}">
        <!-- font-awesome CSS -->
        <link href="{% static 'node_modules/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
        <!-- jquery-ui CSS -->
        <link href="{% static 'node_modules/jquery-ui-dist/jquery-ui.min.css' %}" rel="stylesheet">
        <link href="{% static 'node_modules/jquery-ui-dist/jquery-ui.structure.min.css' %}" rel="stylesheet">
        <link href="{% static 'node_modules/jquery-ui-dist/jquery-ui.theme.min.css' %}" rel="stylesheet">

        <!-- style css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>
    <body>

               
        <div class="container-fluid mt-2">
            <div class="row">
                <!-- <div class="logo"> <a href="/"> <img src="{% static 'images/lgo.png' %}"></a></div> -->
                <div class="col-3 col-sm-3 col-md-4 ">
                    <a class="logo" href="/">
                        <img 
                        src="{% static 'images/logo1.png' %}"
                        class="img-fluid" alt="logo"
                        >
                    </a>
                </div>
                <div class="col-9 col-sm-9 col-md-8 d-flex justify-content-center">
                    <h1 class="d-flex title align-items-center">Pata Bursary</h1>
                </div>
            </div>
        </div>

        {% block header %}
        <div class="row d-flex flex-row">
            
            <div class="col-2 col-lg-6"></div>
            <div class="col-10 col-lg-6">

                <div class="navbar">
                    <a class="active" href="{% url 'bursaryapp:home' %}">&nbsp&nbsp&nbsp&nbsp<i class="fa fa-home fa-fw"></i>Home  </a>
                    {% if user.is_authenticated %}
                    {% if user.is_staff %}
                    <a href="{% url 'bursaryapp:Applicants' %}"> Applicants </i></a>
                    <a href="{% url 'bursaryapp:Addbursary' %}"> Add Bursary </i></a>
                    {% else %}
                    <a href="{% url 'accounts:applicant_dashboard' %}"><i class="fa fa-fw fa-user"></i> My profile</a>
                    {% endif %}
                    <a href="{% url 'logout' %}"> Logout <i class="fa fa-power-off"></i> &nbsp&nbsp&nbsp&nbsp</a>
                    {% else %}
                    <div class="d-flex flex-row">
                        <a href="{% url 'accounts:register' %}"> <i class="fa fa-user-plus"></i> Register  &nbsp&nbsp&nbsp&nbsp</a>
                        <a href="{% url 'accounts:login' %}"> <i class="fa fa-sign-in"></i> Login  &nbsp&nbsp&nbsp&nbsp</a>
                    </div>
                    {% endif %} 
                </div>
            </div>    
        </div>
        {% endblock %}
        


        {% block content %}

        {%endblock%}
        <!--javascript files-->
        <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
        <!--Jquery-ui-->
        <script src="{% static 'node_modules/jquery-ui-dist/jquery-ui.min.js' %}"></script>

        <script src="{% static 'js/scripts' %}"></script>
        
        <script src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
        <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

        <!-- htmx -->
        <!-- <script src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}" defer></script>
        {% django_htmx_script %} -->

    </body>
</html>

templates/home.html
{% extends 'base.html'%}

{% block content%}

<div class="container-fluid">
  <br />
  <div class="body-container pt-lg-4">
    <div class="container-lg">
      <div class="d-flex justify-content-center"><h2>Bursaries</h2></div>


      {% for bursary in object_list %}
      {% if user.is_staff %}

      <div class="row mb-5 bursary-row mb-5 shadow-sm">
        <a href="{% url 'bursaryapp:bursary_details' bursary.pk %}"><span class="bursary-row1"></span></a>
        <div class="col d-flex justify-content-center"><h5><a href="{% url 'bursaryapp:bursary_details' bursary.pk %}">{{ bursary.name_of_bursary }} </a></h5></div>
        <div class="col d-flex justify-content-center"><h5><a href="{% url 'bursaryapp:bursary_details' bursary.pk %}">00 days 00 hours 00 mins </a></h5></div>
      </div>

      {% else %}

      <div class="card  mb-5 shadow-sm">
        <div class="card-body">
          <h5 class="card-title">{{ bursary.name_of_bursary }}</h5>
          <p class="card-text">{{ bursary.description|slice:"100" }}</p>
        </div>
        <div class="card-footer mb-0">
          <div class="row">
            <div class="col-lg-6 d-flex justify-content-start"><p>Application deadline: {{ bursary.end_date }}</p></div>
            
            <div class="col-lg-6 d-flex justify-content-end"><h5><a href="{% url 'bursaryapp:bursary_details' bursary.pk %}" class="btn btn-outline-dark">Read more</a></h5></div>
            
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
      
    </div>
  </div>
</div>
{%endblock%}